### ISSUE TITLE
Runtime bug: "No ACK from tracker" but tracker is disabled

### ISSUE THREAD

**Issue by snytek** [dxx-rebirth/dxx-rebirth#535]
### Environment

https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20200729-win.zip

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [X] Microsoft Windows 10

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

### Description

Host, which tries to open a new multiplayer game gets the message "No ACK from Tracker. Please Check Game Log".

#### Regression status

I've ignored this message a long time already - no version details, sorry.

### Steps to Reproduce

I start the game, configure a multiplayer game and start the game for others to join.
After some seconds the message "No ACK from Tracker. Please Check Game Log".

The gamelog.txt shows the following line (only relevant line):
16:20:18.375 [Tracker] No response from game tracker. Tracker address may be invalid or Tracker may be offline or otherwise unreachable.

In d2x.ini I have this configuration and I think this should disable the tracker:

-no-tracker                   ;Disable tracker (unless overridden by later -tracker_hostaddr)
;-tracker_hostaddr <n>         ;Address of tracker server to register/query games to/from (default: dxxtracker.hopto.org)
;-tracker_hostport <n>         ;Port of tracker server to register/query games to/from (default: 9999)

* Engines affected:
  * [ ] D1X-Rebirth
  * [X] D2X-Rebirth

* Game modes affected:
  * [ ] Single player
  * [X] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

* Players affected by issue:
  * [X] Game host
  * [ ] Game guests

**Comment by vLKp** [comment]
If the advanced menu says `Tracker use disabled`, then it should not be trying to contact the tracker at all, because it does not have an address for the tracker.

**Comment by snytek** [comment]
Nevertheless it happens.
Once I start a game it takes about 7 seconds until the message appears. Once I acknoledge the message it does not show up anymore. Please let me know if I can provide you with any more information or check/try something.

**Comment by vLKp** [comment]
I've gone over the relevant code twice, and assuming the build you are running is using the code I am reviewing, I do not see how this can happen.  Please attach your full ini file and the ngp file for the affected pilot.  Also, if possible, please print the contents of the `Netgame` structure at the time you get the message.  For gdb, breaking in and running `print d2x::Netgame` would suffice.  On Windows, this will be harder, as the Windows native debugger does not understand gcc symbols.

**Comment by snytek** [comment]
I just did a test with a new pilot and got the same message as with my pilot. 
Please find the ini file and the ngp file of the new created test profile attached.
As I am using Windows I can't do the other thing.

[tracker.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/5178254/tracker.zip)

**Comment by snytek** [comment]
I just want to report that this issue is still present in the version:
commit: 1afd0ee , date: 2021/01/26

**Comment by vLKp** [comment]
It still does not happen for me, even using the files you attached.  I do not get the message.  I see in the advanced options that the tracker is disabled.  Inspecting internal state with the debugger also shows the tracker is disabled, as expected.  For the sake of completeness, I downloaded the latest Windows build, disassembled it, and spot-checked that it has the logic I expect should prevent this problem.  It does.  As best I can tell, the reported problem is impossible, and has been impossible since before this issue was filed.

Since I cannot reproduce it, even with your files, and its regression status is unknown, and after reviewing the code three times, I still do not see how this could happen, I do not know what to do for you.  If you could debug to determine why it gets into this state, _maybe_ that would lead to a fix.  Otherwise, there is nothing I can do here.
